import type { SeedTrainingModule } from "@/lib/seed/types";

export const modules: SeedTrainingModule[] = [
  {
    slug: "induccion-general",
    file: "00-induccion-general.md",
    title: "Inducción general",
    description:
      "Introducción a Aion POS, roles de acceso, estados de pedidos y reglas básicas de operación.",
    audience: "Todos",
    estimatedMins: 120,
    orderIndex: 0,
    category: "General",
    level: "Básico",
    gradient: "from-amber-700 to-orange-900",
  },
  {
    slug: "mesero-mesera",
    file: "01-mesero-mesera.md",
    title: "Mesero / Mesera",
    description:
      "Tablero Kanban, atención en salón, coordinación con cocina y bar, historial e incidencias.",
    audience: "Servicio de salón",
    estimatedMins: 180,
    orderIndex: 1,
    category: "Servicio",
    level: "Operativo",
    gradient: "from-rose-600 to-red-800",
  },
  {
    slug: "cocina",
    file: "02-cocina.md",
    title: "Cocina",
    description:
      "Flujo de pedidos en cocina, tiempos, prioridades y comunicación con salón y bar.",
    audience: "Cocinero, Chef, Auxiliar",
    estimatedMins: 180,
    orderIndex: 2,
    category: "Cocina",
    level: "Operativo",
    gradient: "from-orange-500 to-amber-700",
  },
  {
    slug: "bar-bartender",
    file: "03-bar-bartender.md",
    title: "Bar / Bartender",
    description:
      "Bebidas, preparación en barra, coordinación con meseros y estados de pedidos de bar.",
    audience: "Bar",
    estimatedMins: 120,
    orderIndex: 3,
    category: "Bar",
    level: "Operativo",
    gradient: "from-violet-600 to-purple-900",
  },
  {
    slug: "cajero-pos",
    file: "04-cajero-pos.md",
    title: "Cajero / POS",
    description:
      "Punto de venta, facturación, métodos de pago, cierre parcial y manejo de caja.",
    audience: "Caja",
    estimatedMins: 240,
    orderIndex: 4,
    category: "Caja",
    level: "Intermedio",
    gradient: "from-emerald-600 to-teal-800",
  },
  {
    slug: "gerente-supervisor",
    file: "05-gerente-supervisor.md",
    title: "Gerente / Supervisor",
    description:
      "Dashboard, KPIs, supervisión de turno, incidencias y toma de decisiones operativas.",
    audience: "Gerencia",
    estimatedMins: 240,
    orderIndex: 5,
    category: "Gerencia",
    level: "Avanzado",
    gradient: "from-slate-600 to-slate-900",
  },
  {
    slug: "administrador-sistema",
    file: "06-administrador-sistema.md",
    title: "Administrador del sistema",
    description:
      "Configuración multi-restaurante, empleados, menú, mesas, inventario y permisos.",
    audience: "Admin IT / dueño",
    estimatedMins: 360,
    orderIndex: 6,
    category: "Administración",
    level: "Avanzado",
    gradient: "from-indigo-600 to-blue-900",
  },
  {
    slug: "experiencia-cliente",
    file: "07-experiencia-cliente.md",
    title: "Experiencia del cliente",
    description:
      "Menú digital, reservas, pre-orden y estándares de servicio al comensal.",
    audience: "Todos (referencia)",
    estimatedMins: 90,
    orderIndex: 7,
    category: "Servicio",
    level: "Referencia",
    gradient: "from-cyan-500 to-blue-700",
  },
  {
    slug: "apendices",
    file: "08-apendices.md",
    title: "Glosario, evaluaciones y apéndices",
    description:
      "Términos clave, rúbricas de evaluación y material de consulta del programa completo.",
    audience: "Todos",
    estimatedMins: 60,
    orderIndex: 8,
    category: "Referencia",
    level: "Consulta",
    gradient: "from-stone-500 to-stone-700",
  },
];
